[CmdletBinding()]
param(
    [ValidateRange(1, 65535)]
    [int]$LocalPort = 48241,
    [ValidateRange(1, 65535)]
    [int]$RelayPort = 49241,
    [ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')]
    [string]$SshHost = 'dmit',
    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[A-Za-z0-9][A-Za-z0-9._-]*$')]
    [string]$ExpectedRelayHost,
    [string]$InstallRoot = (Join-Path $HOME '.dsv41-connection'),
    [string]$TaskName = 'DSV41 DSH Tunnel'
)

$ErrorActionPreference = 'Stop'
$source = Join-Path $PSScriptRoot 'Connect-DSV41.ps1'
if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
    throw "找不到连接脚本：$source"
}

[System.IO.Directory]::CreateDirectory($InstallRoot) | Out-Null
$destination = Join-Path $InstallRoot 'Connect-DSV41.ps1'
[System.IO.File]::WriteAllText($destination, [System.IO.File]::ReadAllText($source), [System.Text.UTF8Encoding]::new($true))

# Keep the local runtime directory private to the signed-in Windows user.  No
# private key is copied or generated by this installer.
try {
    $acl = Get-Acl -LiteralPath $InstallRoot
    $acl.SetAccessRuleProtection($true, $false)
    $rule = [System.Security.AccessControl.FileSystemAccessRule]::new(
        [System.Security.Principal.WindowsIdentity]::GetCurrent().Name,
        'FullControl', 'ContainerInherit,ObjectInherit', 'None', 'Allow')
    $acl.AddAccessRule($rule)
    Set-Acl -LiteralPath $InstallRoot -AclObject $acl
} catch {
    Write-Warning "无法收紧 $InstallRoot 的 ACL：$($_.Exception.Message)"
}

$powershell = (Get-Command powershell.exe -ErrorAction Stop).Source
$escapedScript = '"' + $destination.Replace('"', '""') + '"'
$argument = @(
    '-NoProfile', '-NonInteractive', '-WindowStyle', 'Hidden', '-ExecutionPolicy', 'Bypass', '-File', $escapedScript,
    '-LocalPort', $LocalPort, '-RelayPort', $RelayPort,
    '-SshHost', ('"' + $SshHost.Replace('"', '""') + '"'),
    '-ExpectedRelayHost', ('"' + $ExpectedRelayHost.Replace('"', '""') + '"'),
    '-ConfigRoot', ('"' + $InstallRoot.Replace('"', '""') + '"')
) -join ' '

$action = New-ScheduledTaskAction -Execute $powershell -Argument $argument
$trigger = New-ScheduledTaskTrigger -AtLogOn -User ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name)
$principal = New-ScheduledTaskPrincipal -UserId ([System.Security.Principal.WindowsIdentity]::GetCurrent().Name) `
    -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Seconds 0) -MultipleInstances IgnoreNew -StartWhenAvailable

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Principal $principal -Settings $settings `
    -Description 'Keeps the loopback-only DSV41 ModelScope tunnel available for DSH.' -Force | Out-Null
Start-ScheduledTask -TaskName $TaskName
Write-Host "已安装并启动当前用户的计划任务：$TaskName"
Write-Host "DSH 的 OpenAI 兼容 Base URL： http://127.0.0.1:$LocalPort/v1"
